2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_setup.py:_flush():76] Configure stats pid to 1097093
2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_setup.py:_flush():76] Loading settings from /home/shuvrajeet/.config/wandb/settings
2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_setup.py:_flush():76] Loading settings from /home/shuvrajeet/Documents/GitHub/IIT_Madras_days/Classes/DL/Assignment1/wandb/settings
2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'Numpy-DL2', 'entity': 'shuvrajeet', 'root_dir': '/home/shuvrajeet/Documents/GitHub/IIT_Madras_days/Classes/DL/Assignment1', 'run_id': 't1ohatwi', 'sweep_param_path': '/home/shuvrajeet/Documents/GitHub/IIT_Madras_days/Classes/DL/Assignment1/wandb/sweep-2sztk7c8/config-t1ohatwi.yaml', 'sweep_id': '2sztk7c8'}
2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'Classes/DL/Assignment1/neural_network.py', 'program_abspath': '/home/shuvrajeet/Documents/GitHub/IIT_Madras_days/Classes/DL/Assignment1/neural_network.py', 'program': '/home/shuvrajeet/Documents/GitHub/IIT_Madras_days/Classes/DL/Assignment1/neural_network.py'}
2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:_log_setup():524] Logging user logs to /home/shuvrajeet/Documents/GitHub/IIT_Madras_days/Classes/DL/Assignment1/wandb/run-20231117_112101-t1ohatwi/logs/debug.log
2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:_log_setup():525] Logging internal logs to /home/shuvrajeet/Documents/GitHub/IIT_Madras_days/Classes/DL/Assignment1/wandb/run-20231117_112101-t1ohatwi/logs/debug-internal.log
2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:init():564] calling init triggers
2023-11-17 11:21:01,300 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:init():571] wandb.init called with sweep_config: {'activation_functions': 'relu', 'batch_size': 32, 'learning_rate': 0.0001, 'number_of_epochs': 10, 'number_of_hidden_layers': 4, 'optimizer': 'adam', 'size_of_every_hidden_layer': 64, 'weight_decay': 0.0005, 'weight_initialisation': 'xavier_normal'}
config: {}
2023-11-17 11:21:01,301 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:init():614] starting backend
2023-11-17 11:21:01,301 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:init():618] setting up manager
2023-11-17 11:21:01,304 INFO    Thread-178 (_run_job):1097093 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-11-17 11:21:01,306 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:init():624] backend started and connected
2023-11-17 11:21:01,311 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_config_callback():1342] config_cb None None {'activation_functions': 'relu', 'batch_size': 32, 'learning_rate': 0.0001, 'number_of_epochs': 10, 'number_of_hidden_layers': 4, 'optimizer': 'adam', 'size_of_every_hidden_layer': 64, 'weight_decay': 0.0005, 'weight_initialisation': 'xavier_normal'}
2023-11-17 11:21:01,311 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:init():716] updated telemetry
2023-11-17 11:21:01,314 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-11-17 11:21:01,979 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_on_init():2254] communicating current version
2023-11-17 11:21:02,171 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_on_init():2263] got version response 
2023-11-17 11:21:02,172 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:init():800] starting run threads in backend
2023-11-17 11:21:04,838 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_console_start():2233] atexit reg
2023-11-17 11:21:04,839 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2023-11-17 11:21:04,839 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_redirect():2153] Wrapping output streams.
2023-11-17 11:21:04,839 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_redirect():2178] Redirects installed.
2023-11-17 11:21:04,839 INFO    Thread-178 (_run_job):1097093 [wandb_init.py:init():841] run started, returning control to user process
2023-11-17 11:21:15,805 INFO    Thread-2 (_heartbeat):1097093 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvrajeet/miniconda3/envs/ResearchIITM/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1006)')))
2023-11-17 11:21:43,264 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_finish():1962] finishing run shuvrajeet/Numpy-DL2/t1ohatwi
2023-11-17 11:21:43,264 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2023-11-17 11:21:43,265 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_restore():2185] restore
2023-11-17 11:21:43,268 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_restore():2191] restore done
2023-11-17 11:26:12,532 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_footer_history_summary_info():3760] rendering history
2023-11-17 11:26:12,533 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_footer_history_summary_info():3792] rendering summary
2023-11-17 11:26:12,534 INFO    Thread-178 (_run_job):1097093 [wandb_run.py:_footer_sync_info():3719] logging synced files
